creditapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns=[
path('home/',views.home,name="home"),
path('adduser/',views.adduser,name="adduser"),
path('submituser/',views.submituser,name="submituser"),

path('userpage/',views.userpage,name="userpage"),
path('transfer/',views.transfer,name="transfer"),




]

credittransfer/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('creditapp/',include('creditapp.urls')),
]

creditapp/models.py
from django.db import models
from django.utils.timezone import now
# Create your models here.

class User(models.Model):
    name=models.CharField(max_length=100)
    email=models.CharField(max_length=50)
    contact=models.CharField(max_length=50)
    credit=models.FloatField(default=500)
    gender=models.CharField(max_length=40)

class Transaction(models.Model):
    received=models.CharField(max_length=100)
    sent=models.CharField(max_length=100)
    credit=models.FloatField()
    date=models.DateField(default=now)

creditapp/views.py
from django.shortcuts import render
from creditapp.models import User,Transaction
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
# Create your views here.

def home(request):
    users=User.objects.all()




    return render(request,'creditapp/home.html',{
    'user':users,
    })

def adduser(request):
    return render(request,'creditapp/adduser.html')



def userpage(request):
    email=request.POST.get('email')
    user=User.objects.filter(email=email)
    transsend=Transaction.objects.filter(sent=email)
    transreceive=Transaction.objects.filter(received=user[0].name)
    allusers=User.objects.exclude(email=email)

    print(allusers)
    receivedl=[]
    for i in transreceive:
        ur=User.objects.get(email=i.sent)
        print(i.sent)
        print(ur)
        print('ggg')
        receivedl.append({'name':ur.name,'credit':i.credit,'date':i.date
        })
    aa=''
    return render(request,'creditapp/userpage.html',{
    'user':user[0],'ts':transsend,'tr':receivedl,'all':allusers,'lesscr':aa,
    })


def transfer(request):
    name=request.POST.get('name')
    credits=request.POST.get('credits')
    email=request.POST.get('email')
    u=User.objects.get(email=email)
    transsend=Transaction.objects.filter(sent=email)
    transreceive=Transaction.objects.filter(received=u.name)
    print('lllllllllllll')
    print(transreceive)
    allusers=User.objects.exclude(email=email)
    receivedl=[]
    for i in transreceive:
        ur=User.objects.get(email=i.sent)
        print(i.sent)
        print(ur)
        print('ggg')
        receivedl.append({'name':ur.name,'credit':i.credit,'date':i.date
        })
    if float(credits)>u.credit:
        return render(request,'creditapp/userpage.html',{
        'user':u,'ts':transsend,'tr':receivedl,'all':allusers,'lesscr':'not enough balance',
        })

    t=Transaction(received=name,sent=email,credit=credits)
    t.save()


    u.credit-=float(credits)
    rn=User.objects.get(name=name)
    rn.credit+=float(credits)
    rn.save()
    u.save()
    transsend=Transaction.objects.filter(sent=email)
    transreceive=Transaction.objects.filter(received=u.name)
    print('lllllllllllll')
    print(transreceive)
    allusers=User.objects.exclude(email=email)
    receivedl=[]
    for i in transreceive:
        ur=User.objects.get(email=i.sent)
        print(i.sent)
        print(ur)
        print('ggg')
        receivedl.append({'name':ur.name,'credit':i.credit,'date':i.date
        })
    a=''

    return render(request,'creditapp/userpage.html',{
    'user':u,'ts':transsend,'tr':receivedl,'all':allusers,'lesscr':a,
    })



def submituser(request):
    name=request.POST.get('name')
    email=request.POST.get('email')
    contact=request.POST.get('number')
    gender=request.POST.get('gender')







    sa=User.objects.filter(email=email)
    if len(sa):
        return HttpResponseRedirect(reverse('adduser')+'?auth1=true')
    else:

        u=User(name=name,email=email,contact=contact,gender=gender)

        u.save()

    return HttpResponseRedirect(reverse('home'))

creditapp/templates/creditapp/adduser.html
<!doctype html>
<html>
<head>
  <meta charset=utf-8>
  <title>add user</title>

  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">CreditApp</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'home' %}">Home</a></li>
      <li><a href="{% url 'adduser' %}">Add User</a></li>

    </ul>
  </div>
  </nav>

  <!------ Include the above in your HEAD tag ---------->

  <div class="container">

      <div id="signupbox" style=" margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
          <div class="panel panel-info">
              <div class="panel-heading">
                  <div class="panel-title">Sign Up</div>

              </div>
              <div class="panel-body" >


                      {% if request.GET.auth1 %}
                <p class="text-center" style="color:red; font-size:25px;">username exists</p>
                {% endif %}
                      <form  class="form-horizontal" method="post"  action="{% url 'submituser' %}">

                            {% csrf_token %}


                          <div id="div_id_email" class="form-group required">
                              <label for="id_email" class="control-label col-md-4  requiredField"> E-mail<span class="asteriskField">*</span> </label>
                              <div class="controls col-md-8 ">
                                  <input class="input-md emailinput form-control" id="id_email" name="email" placeholder="Your current email address" style="margin-bottom: 10px" type="email" required/>
                              </div>
                          </div>


                          <div id="div_id_name" class="form-group required">
                              <label for="id_name" class="control-label col-md-4  requiredField"> full name<span class="asteriskField">*</span> </label>
                              <div class="controls col-md-8 ">
                                  <input class="input-md textinput textInput form-control" id="id_name" name="name" placeholder="Your Frist name and Last name" style="margin-bottom: 10px" type="text" required/>
                              </div>
                          </div>
                          <div id="div_id_gender" class="form-group required">
                              <label for="id_gender"  class="control-label col-md-4  requiredField"> Gender<span class="asteriskField">*</span> </label>
                              <div class="controls col-md-8 "  style="margin-bottom: 10px" >
                                   <label class="radio-inline"> <input type="radio" name="gender" id="id_gender_1" value="M"  style="margin-bottom: 10px" checked>Male</label>
                                   <label class="radio-inline"> <input type="radio" name="gender" id="id_gender_2" value="F"  style="margin-bottom: 10px">Female </label>
                              </div>
                          </div>

                          <div id="div_id_number" class="form-group required">
                               <label for="id_number" class="control-label col-md-4  requiredField"> contact number<span class="asteriskField">*</span> </label>
                               <div class="controls col-md-8 ">
                                   <input class="input-md textinput textInput form-control" id="id_number" name="number" placeholder="provide your number" style="margin-bottom: 10px" type="text" required/>
                              </div>
                          </div>


                          <div class="form-group">
                              <div class="aab controls col-md-4 "></div>
                              <div class="controls col-md-8 ">
                                  <input type="submit" name="Signup" value="Signup" class="btn btn-primary btn btn-info" id="submit-id-signup" />

                              </div>
                          </div>

                      </form>


              </div>
          </div>
      </div>
  </div>






  </div>



</body>
</html>

creditapp/templates/creditapp/home.html
<!doctype html>
<html>
<head>
  <meta charset=utf-8>
  <title>home</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

<style media="screen">
  h4{
    display:inline;
  }
</style>
</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">CreditApp</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="{% url 'adduser' %}">Add User</a></li>
    
    </ul>
  </div>
</nav>



<div class="container">

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>email</th>
        <th>Credits</th>
        <th>View</th>
      </tr>
    </thead>
    <tbody>
        {% for users in user %}
      <tr>
        <td>{{users.name}}</td>
        <td>{{users.email}}</td>
        <td>{{users.credit}}</td>
        <td>
        <form class="" action="{% url 'userpage' %}" method="post">
           {% csrf_token %}
          <input type="hidden" name="email" value="{{users.email}}">
        <button type="submit" class="btn btn-success" >View</button>
        </form>
        </td>
      </tr>
        {% endfor %}

    </tbody>
  </table>
</div>



</body>
</html>

creditapp/templates/creditapp/userpage.html
<!doctype html>
<html>
<head>
  <meta charset=utf-8>
  <title>userpage</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

<style media="screen">
  h4{
    display:inline;
  }
</style>
</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">CreditApp</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'home' %}">Home</a></li>
      <li><a href="{% url 'adduser' %}">Add User</a></li>

    </ul>
  </div>
</nav>

 <h4 style="margin-left: 500px;" >Welcome {{user.name}}</h4>

<p class="text-center" style="color:red; font-size:25px;">{{lesscr}}</p>

<div class="container">

    <div id="signupbox" style=" margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="panel-title">Transfer Credits</div>

            </div>
            <div class="panel-body" >



                    <form  class="form-horizontal" method="post"  action="{% url 'transfer' %}">

                          {% csrf_token %}

                          <div id="div_id_name" class="form-group required">
                              <label for="id_name" class="control-label col-md-4  requiredField"> full name<span class="asteriskField">*</span> </label>
                              <div class="controls col-md-8 ">

                                  <select class="form-control" name="name">
                                      {% for u in all %}


                      <option value="{{u.name}}">{{u.name}}</option>




                                    {% endfor %}
                                  </select>
                              </div>
                          </div>

                          <div id="div_id_number" class="form-group required">
                               <label for="id_number" class="control-label col-md-4  requiredField"> available credits<span class="asteriskField">*</span> </label>
                               <div class="controls col-md-8 ">
                                   <input class="input-md textinput textInput form-control" id="id_number" name="number" value="{{user.credit}}" style="margin-bottom: 10px" type="text" readonly/>
                              </div>
                          </div>



                        <div id="div_id_number" class="form-group required">
                             <label for="id_number" class="control-label col-md-4  requiredField">credits<span class="asteriskField">*</span> </label>
                             <div class="controls col-md-8 ">
                                 <input class="input-md textinput textInput form-control" id="id_number" name="credits" placeholder="credits to transfer" style="margin-bottom: 10px" type="number" min="1" />
                            </div>
                        </div>
<input type="hidden" name="email" value="{{user.email}}">

                        <div class="form-group">
                            <div class="aab controls col-md-4 "></div>
                            <div class="controls col-md-8 ">

                                <input type="submit" name="" value="Transfer" class="btn btn-primary btn btn-info" id="submit-id-signup" />

                            </div>
                        </div>

                    </form>


            </div>
            </div>
            </div>



<div class="container row">
<div class="col-sm-5">


  <table class="table table-hover ">
    <thead>
      <tr>
        <th>Name</th>

        <th>Credits Recevied</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
        {% for r in tr %}
    <tr>
      <td>{{r.name}}</td>
      <td>{{r.credit}}</td>
      <td>{{r.date}}</td>
    </tr>
        {% endfor %}

    </tbody>
  </table>
  </div>
  <div class="col-sm-5">


  <table class="table table-hover ">
    <thead>
      <tr>
        <th>Name</th>

        <th>Credits Transfered</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
        {% for s in ts %}
    <tr>
      <td>{{s.received}}</td>
      <td>{{s.credit}}</td>
      <td>{{s.date}}</td>
    </tr>
    {% endfor %}

    </tbody>
  </table>
    </div>
</div>



</body>
</html>